version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: doc-blacklist-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: doc_user
      MONGO_INITDB_ROOT_PASSWORD: doc_pass
    ports:
      - "27017:27017"
  service:
    build:
      context: ./service
      dockerfile: Dockerfile.service
    container_name: doc-blacklist-service
    ports:
      - "5000:5000"
    depends_on:
      - "mongodb"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    container_name: doc-blacklist-ui
    ports:
      - "3000:3000"