FROM node:12.16.1-alpine
RUN mkdir -p /app/src
WORKDIR /app
COPY src /app/src
COPY tsconfig.json /app/tsconfig.json
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
CMD ["npm", "run", "dev"]