FROM node:12.16.1-alpine
EXPOSE 3000
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY src /app/src
COPY public /app/public
COPY tsconfig.json /app/tsconfig.json
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

RUN npm install
CMD ["npm", "run", "start"]
